#!/bin/bash
# Script to help set up GitHub repository for fraud detection project

echo "=== GitHub Repository Setup Instructions ==="
echo ""
echo "1. Go to https://github.com/new"
echo "2. Repository name: fraud-detection"
echo "3. Description: Real-time credit card fraud detection on AWS"
echo "4. Make it Public or Private (your choice)"
echo "5. DO NOT initialize with README (we already have one)"
echo "6. Click 'Create repository'"
echo ""
echo "7. After creating, run these commands:"
echo ""
echo "   git remote add origin https://github.com/YOUR_USERNAME/fraud-detection.git"
echo "   git push -u origin main"
echo ""
echo "8. Then add GitHub Secrets (Settings → Secrets and variables → Actions):"
echo "   - AWS_ACCESS_KEY_ID: (your AWS access key)"
echo "   - AWS_SECRET_ACCESS_KEY: (your AWS secret key)"
echo "   - SAGEMAKER_ENDPOINT_NAME: fraud-xgb-endpoint"
echo "   - SNS_TOPIC_ARN: arn:aws:sns:ap-south-1:476114148593:fraud-alerts"
echo ""
echo "=== Current Project Status ==="
echo "✅ Git repository initialized"
echo "✅ Initial commit created"
echo "✅ SageMaker endpoint deploying (check status below)"
echo "✅ Lambda environment variables updated"
echo ""
